# Generated by Django 4.2.5 on 2023-09-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='budget',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
