# Generated by Django 4.2.5 on 2023-09-29 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0002_alter_budget_options_budget_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={"ordering": ["category__order", "order", "id"]},
        ),
    ]
