# Generated by Django 4.2.5 on 2024-04-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_alter_budget_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ("date",)},
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_by",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Other"), (1, "Groom"), (2, "Bride")], default=1
            ),
        ),
    ]
