# Generated by Django 4.2.5 on 2023-09-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lable", models.CharField(max_length=100)),
                ("note", models.TextField()),
                ("date", models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                "verbose_name_plural": "Logbook",
                "ordering": ["date"],
            },
        ),
    ]
