# Generated by Django 4.2.5 on 2023-09-30 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guest", "0002_alter_guest_options_guest_drinks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guest",
            options={
                "ordering": ["category__order", "order", "id"],
                "verbose_name_plural": " Guest List",
            },
        ),
    ]
