# Generated by Django 4.2.5 on 2024-04-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0003_alter_guest_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guest",
            options={
                "ordering": ["category__order", "order", "name"],
                "verbose_name_plural": " Guest List",
            },
        ),
    ]
